name: CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  test:
    name: Test on angular ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        angular_version: ['7', '8', '9']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Angular/cli ${{ matrix.angular_version }}
      uses: actions/setup-angular@v1
      with:
        angular-version: ${{ matrix.angular_version }}
      
    - name: npm install
      run: |
        npm install
        npm run build --if-present
        npm test
